/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as PortalTrackerRouteImport } from './routes/portal/tracker'
import { Route as PortalOrdersRouteImport } from './routes/portal/orders'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalComplianceRouteImport } from './routes/portal/compliance'
import { Route as PortalCatalogRouteImport } from './routes/portal/catalog'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as CatalogSlugRouteImport } from './routes/catalog/$slug'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { ServerRoute as ApiRfqSubmitServerRouteImport } from './routes/api/rfq/submit'
import { ServerRoute as ApiSourcingRequestServerRouteImport } from './routes/api/sourcing/request'
import { ServerRoute as ApiPoUpdateServerRouteImport } from './routes/api/po/update'

const rootServerRouteImport = createServerRootRoute()

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTrackerRoute = PortalTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalComplianceRoute = PortalComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCatalogRoute = PortalCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PortalRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRfqSubmitServerRoute = ApiRfqSubmitServerRouteImport.update({
  id: '/api/rfq/submit',
  path: '/api/rfq/submit',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiSourcingRequestServerRoute =
  ApiSourcingRequestServerRouteImport.update({
    id: '/api/sourcing/request',
    path: '/api/sourcing/request',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiPoUpdateServerRoute = ApiPoUpdateServerRouteImport.update({
  id: '/api/po/update',
  path: '/api/po/update',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/documents': typeof AdminDocumentsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/tracker': typeof PortalTrackerRoute
  '/catalog': typeof CatalogIndexRoute
  '/news': typeof NewsIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/tracker': typeof PortalTrackerRoute
  '/catalog': typeof CatalogIndexRoute
  '/news': typeof NewsIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/documents': typeof AdminDocumentsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/catalog': typeof PortalCatalogRoute
  '/portal/compliance': typeof PortalComplianceRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/tracker': typeof PortalTrackerRoute
  '/catalog/': typeof CatalogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portal'
    | '/admin/documents'
    | '/catalog/$slug'
    | '/news/$slug'
    | '/portal/catalog'
    | '/portal/compliance'
    | '/portal/dashboard'
    | '/portal/orders'
    | '/portal/tracker'
    | '/catalog'
    | '/news'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/documents'
    | '/catalog/$slug'
    | '/news/$slug'
    | '/portal/catalog'
    | '/portal/compliance'
    | '/portal/dashboard'
    | '/portal/orders'
    | '/portal/tracker'
    | '/catalog'
    | '/news'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portal'
    | '/admin/documents'
    | '/catalog/$slug'
    | '/news/$slug'
    | '/portal/catalog'
    | '/portal/compliance'
    | '/portal/dashboard'
    | '/portal/orders'
    | '/portal/tracker'
    | '/catalog/'
    | '/news/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortalRoute: typeof PortalRouteWithChildren
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/rfq/submit': typeof ApiRfqSubmitServerRoute
  '/api/sourcing/request': typeof ApiSourcingRequestServerRoute
  '/api/po/update': typeof ApiPoUpdateServerRoute
}
export interface FileServerRoutesByTo {
  '/api/rfq/submit': typeof ApiRfqSubmitServerRoute
  '/api/sourcing/request': typeof ApiSourcingRequestServerRoute
  '/api/po/update': typeof ApiPoUpdateServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/rfq/submit': typeof ApiRfqSubmitServerRoute
  '/api/sourcing/request': typeof ApiSourcingRequestServerRoute
  '/api/po/update': typeof ApiPoUpdateServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/rfq/submit' | '/api/sourcing/request' | '/api/po/update'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/rfq/submit' | '/api/sourcing/request' | '/api/po/update'
  id: '__root__' | '/api/rfq/submit' | '/api/sourcing/request' | '/api/po/update'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiRfqSubmitServerRoute: typeof ApiRfqSubmitServerRoute
  ApiSourcingRequestServerRoute: typeof ApiSourcingRequestServerRoute
  ApiPoUpdateServerRoute: typeof ApiPoUpdateServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tracker': {
      id: '/portal/tracker'
      path: '/tracker'
      fullPath: '/portal/tracker'
      preLoaderRoute: typeof PortalTrackerRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/compliance': {
      id: '/portal/compliance'
      path: '/compliance'
      fullPath: '/portal/compliance'
      preLoaderRoute: typeof PortalComplianceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/catalog': {
      id: '/portal/catalog'
      path: '/catalog'
      fullPath: '/portal/catalog'
      preLoaderRoute: typeof PortalCatalogRouteImport
      parentRoute: typeof PortalRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/rfq/submit': {
      id: '/api/rfq/submit'
      path: '/api/rfq/submit'
      fullPath: '/api/rfq/submit'
      preLoaderRoute: typeof ApiRfqSubmitServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/sourcing/request': {
      id: '/api/sourcing/request'
      path: '/api/sourcing/request'
      fullPath: '/api/sourcing/request'
      preLoaderRoute: typeof ApiSourcingRequestServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/po/update': {
      id: '/api/po/update'
      path: '/api/po/update'
      fullPath: '/api/po/update'
      preLoaderRoute: typeof ApiPoUpdateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalCatalogRoute: typeof PortalCatalogRoute
  PortalComplianceRoute: typeof PortalComplianceRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalTrackerRoute: typeof PortalTrackerRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCatalogRoute: PortalCatalogRoute,
  PortalComplianceRoute: PortalComplianceRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalTrackerRoute: PortalTrackerRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortalRoute: PortalRouteWithChildren,
  AdminDocumentsRoute: AdminDocumentsRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiRfqSubmitServerRoute: ApiRfqSubmitServerRoute,
  ApiSourcingRequestServerRoute: ApiSourcingRequestServerRoute,
  ApiPoUpdateServerRoute: ApiPoUpdateServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
